# ==========================================
# 1. Compiler and Flags
# ==========================================
CXX      := g++
CXXFLAGS := -Wall -Wextra -std=c++11 -g -I.
LDFLAGS  := 

# Name of your final executable
TARGET   := engine

# ==========================================
# 2. Automatic File Discovery (Root Directory)
# ==========================================
# Find all .cpp files in the current directory
SRCS := $(wildcard *.cpp)

# Create a list of corresponding .o object files
OBJS := $(SRCS:.cpp=.o)

# Create a list of dependency files generated by GCC
DEPS := $(OBJS:.o=.d)

# ==========================================
# 3. Build Rules
# ==========================================

.PHONY: all clean run # signify that these commands are not files to prevent potential bugs

# Default rule: builds the executable
all: $(TARGET)

# Link all compiled object files into the target executable
$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)
	@echo "Build successful: ./$(TARGET)"

# Compile each .cpp into a .o file
# -MMD -MP automatically creates .d files to track header (.h) changes
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

# Include generated header dependencies so editing a .h triggers a rebuild
-include $(DEPS)

# Run the compiled program
run: $(TARGET)
	./$(TARGET)

# Clean up build output (.o, .d, and executable)
clean:
	rm -f $(OBJS) $(DEPS) $(TARGET)
	@echo "Cleaned all build artifacts."