# ==========================================
# 1. Compiler and Flags
# ==========================================
CXX      := g++
CXXFLAGS := -Wall -Wextra -std=c++11 -g -I.
LDFLAGS  := 

# Name of your final executable
TARGET   := engine

# Name of the submission zip file
ZIP_NAME := submission.zip

# ==========================================
# 2. Automatic File Discovery (Root Directory)
# ==========================================
# Find all .cpp and .h files in the current directory
SRCS := $(wildcard *.cpp)
HDRS := $(wildcard *.h)

# Create a list of corresponding .o object files
OBJS := $(SRCS:.cpp=.o)

# Create a list of dependency files generated by GCC
DEPS := $(OBJS:.o=.d)

# ==========================================
# 3. Build Rules
# ==========================================

.PHONY: all clean run zip

# Default rule: builds the executable
all: $(TARGET)

# Link all compiled object files into the target executable
$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $@ $(LDFLAGS)
	@echo "Build successful: ./$(TARGET)"

# Compile each .cpp into a .o file
# -MMD -MP automatically creates .d files to track header (.h) changes
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

# Include generated header dependencies so editing a .h triggers a rebuild
-include $(DEPS)

# Run the compiled program
run: $(TARGET)
	./$(TARGET)

# Package source files, answers.pdf, and Makefile into a zip
zip:
	zip $(ZIP_NAME) $(SRCS) $(HDRS) answers.pdf Makefile
	@echo "Successfully created $(ZIP_NAME)"

# Clean up build output (.o, .d, executable, and zip file)
clean:
	rm -f $(OBJS) $(DEPS) $(TARGET) $(ZIP_NAME)
	@echo "Cleaned all build artifacts."